function onCreate() 
	precacheSound('intro3')
	precacheSound('intro2')
	precacheSound('intro1')
	precacheSound('introGo')
	precacheImage('onyourmarks')
	precacheImage('ready')
	precacheImage('set')
	precacheImage('go')
	makeLuaSprite('three', 'count/onyourmarks', 0, 0)
    setProperty('three.scale.x',1.2)
    setProperty('three.scale.y',1.2)
	screenCenter('three', 'xy')
	setObjectCamera('three', 'OTHER')
	doTweenAngle('whatd', 'three', 25, 0.000001, 'cubeOut')
	makeLuaSprite('two', 'count/ready', 0, 0)
    setProperty('two.scale.x',1.2)
    setProperty('two.scale.y',1.2)
	screenCenter('two', 'xy')
	setObjectCamera('two', 'OTHER')
	doTweenAngle('dioe', 'two', -25, 0.000001, 'cubeOut')
	makeLuaSprite('one', 'count/set', 0, 0)
    setProperty('one.scale.x',1.2)
    setProperty('one.scale.y',1.2)
	screenCenter('one', 'xy')
	setObjectCamera('one', 'OTHER')
	doTweenAngle('sssssss', 'one', 25, 0.000001, 'cubeOut')
	makeLuaSprite('go', 'count/go', 0, 0)
    setProperty('go.scale.x',1.4)
    setProperty('go.scale.y',1.4)
	screenCenter('go', 'xy')
	setObjectCamera('go', 'OTHER')
	setProperty('countdownReady.visible', false)
	setProperty('countdownSet.visible', false)
	setProperty('countdownGo.visible', false)
	setProperty('introSoundsSuffix', '-NADALAVERGAEXACTO')
end
function onCountdownTick(counter)
	if counter == 0 then
		addLuaSprite('three')
		playSound('intro3')
		doTweenAlpha('3333','three',0,0.5,'linear')
		doTweenX('3ahhdshad', 'three.scale', 1, 0.5, 'cubeOut')
        doTweenY('3grrrrr', 'three.scale', 1, 0.5, 'cubeOut') 
		doTweenAngle('dddd', 'three', 1, 0.5, 'cubeOut')
	elseif counter == 1 then
		removeLuaSprite('three', false)
		addLuaSprite('two')
		playSound('intro2')
		doTweenAlpha('what2','two',0,0.5,'linear')
		doTweenX('fdfdsf', 'two.scale', 1, 0.5, 'cubeOut')
        doTweenY('3gaaarrrrr', 'two.scale', 1, 0.5, 'cubeOut') 
		doTweenAngle('sadsadsssdsfdsfdsadsadsa', 'two', 1, 0.5, 'cubeOut')
		setProperty('countdownReady.visible', false)
	elseif counter == 2 then
		removeLuaSprite('two', false)
		addLuaSprite('one')
		playSound('intro1')
		doTweenAlpha('31111','one',0,0.5,'linear')
		doTweenX('3ahhdsdsfdsfdsfhad', 'one.scale', 1, 0.5, 'cubeOut')
        doTweenY('3grrrfdsfdsfdsrr', 'one.scale', 1, 0.5, 'cubeOut') 
		doTweenAngle('sadsadsadeeeeeeeeeeeeeesadsa', 'one', 1, 0.5, 'cubeOut')
		setProperty('countdownSet.visible', false)
	elseif counter == 3 then
		removeLuaSprite('one', false)
		addLuaSprite('go')
		playSound('introGo')
		doTweenAlpha('goe','go',0,0.5,'linear')
		doTweenX('GOAAAAAAAAAAAAAA', 'go.scale', 1, 0.5, 'cubeOut')
        doTweenY('bitch', 'go.scale', 1, 0.5, 'cubeOut') 
		setProperty('countdownGo.visible', false)
	elseif counter == 4 then
		removeLuaSprite('go')
	end
end